<?php
/**
 * @file
 *  Git module
 */

define('GIT_CMD', escapeshellcmd(variable_get('git_cmd', '/usr/bin/git')));

/**
 * Implements hook_splclassloader_namespaces().
 */
function git_splclassloader_namespaces() {
  return array('Git' => __DIR__);
}

/**
 * Provides a reusable instance of Git\Client from the gitlistlib library.
 *
 * @param string $id Optional identifier for this client to help avoid conflicts between different modules (eg. with different SSH Passphrases)
 * @return Git\Client
 *  A git client
 */
function git_get_client($id = '') {
  $client =& drupal_static(__FUNCTION__ . ($id ? "_$id" : ''));

  if (empty($client)) {
    $client = new Git\Client(array('path' => GIT_CMD, 'hidden' => array()));
    $client->setSSHPassphrase(variable_get("git_sshpass_$id", NULL));

    global $user;
    $client->getGitEnvironment()->setAll(array(
      'GIT_AUTHOR_NAME' => format_username($user),
      'GIT_AUTHOR_EMAIL' => $user->mail,
      'GIT_COMMITTER_NAME' => format_username($user),
      'GIT_COMMITTER_EMAIL' => $user->mail,
    ));
  }

  return $client;
}

/**
 * Provides a Git\Repository reference for the repo this file resides in.
 *
 * @return Git\Repository
 *  The git repo that this file resides in
 */
function git_get_repo() {
  $git = git_get_client();
  return $git->getRepository(__DIR__);
}
